// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sample.Contracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ContainerShipped : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ContainerShipped"",""namespace"":""Sample.Contracts"",""fields"":[{""name"":""OrderNumber"",""type"":""string"",""displayName"":""Order Number"",""maxLength"":100},{""name"":""LicensePlateNumber"",""type"":""string"",""displayName"":""LicensePlateNumber"",""maxLength"":100},{""name"":""Carrier"",""type"":""string"",""displayName"":""Carrier"",""maxLength"":50},{""name"":""TrackingNumber"",""type"":""string"",""displayName"":""Tracking Number"",""maxLength"":100}],""displayName"":""Container Shipped""}");
		private string _OrderNumber;
		private string _LicensePlateNumber;
		private string _Carrier;
		private string _TrackingNumber;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ContainerShipped._SCHEMA;
			}
		}
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				this._OrderNumber = value;
			}
		}
		public string LicensePlateNumber
		{
			get
			{
				return this._LicensePlateNumber;
			}
			set
			{
				this._LicensePlateNumber = value;
			}
		}
		public string Carrier
		{
			get
			{
				return this._Carrier;
			}
			set
			{
				this._Carrier = value;
			}
		}
		public string TrackingNumber
		{
			get
			{
				return this._TrackingNumber;
			}
			set
			{
				this._TrackingNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderNumber;
			case 1: return this.LicensePlateNumber;
			case 2: return this.Carrier;
			case 3: return this.TrackingNumber;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderNumber = (System.String)fieldValue; break;
			case 1: this.LicensePlateNumber = (System.String)fieldValue; break;
			case 2: this.Carrier = (System.String)fieldValue; break;
			case 3: this.TrackingNumber = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
