// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sample.Contracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ProductPicked : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProductPicked"",""namespace"":""Sample.Contracts"",""fields"":[{""name"":""OrderNumber"",""type"":""string"",""displayName"":""Order Number"",""maxLength"":100},{""name"":""OrderLine"",""type"":""long"",""displayName"":""OrderLine""},{""name"":""Sku"",""type"":""string"",""displayName"":""Sku"",""maxLength"":100},{""name"":""SerialNumber"",""type"":""string"",""displayName"":""SerialNumber"",""maxLength"":100},{""name"":""LicensePlateNumber"",""type"":""string"",""displayName"":""LicensePlateNumber"",""maxLength"":100}],""displayName"":""Product Picked""}");
		private string _OrderNumber;
		private long _OrderLine;
		private string _Sku;
		private string _SerialNumber;
		private string _LicensePlateNumber;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProductPicked._SCHEMA;
			}
		}
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				this._OrderNumber = value;
			}
		}
		public long OrderLine
		{
			get
			{
				return this._OrderLine;
			}
			set
			{
				this._OrderLine = value;
			}
		}
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				this._SerialNumber = value;
			}
		}
		public string LicensePlateNumber
		{
			get
			{
				return this._LicensePlateNumber;
			}
			set
			{
				this._LicensePlateNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderNumber;
			case 1: return this.OrderLine;
			case 2: return this.Sku;
			case 3: return this.SerialNumber;
			case 4: return this.LicensePlateNumber;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderNumber = (System.String)fieldValue; break;
			case 1: this.OrderLine = (System.Int64)fieldValue; break;
			case 2: this.Sku = (System.String)fieldValue; break;
			case 3: this.SerialNumber = (System.String)fieldValue; break;
			case 4: this.LicensePlateNumber = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
