// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sample.Contracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ShipmentManifestReceived : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ShipmentManifestReceived"",""namespace"":""Sample.Contracts"",""fields"":[{""name"":""SourceSystemId"",""type"":""string"",""displayName"":""Source System Id"",""maxLength"":100},{""name"":""EventId"",""type"":""string"",""displayName"":""Event Id"",""maxLength"":100},{""name"":""Timestamp"",""type"":""string"",""displayName"":""Timestamp"",""maxLength"":50},{""name"":""PurchaseOrderNumber"",""type"":""string"",""displayName"":""Purchase Order Number"",""maxLength"":100},{""name"":""DeliveryLocation"",""type"":""int"",""displayName"":""Delivery Location""},{""name"":""Items"",""default"":[],""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Product"",""namespace"":""Sample.Contracts"",""fields"":[{""name"":""Sku"",""type"":""string"",""displayName"":""Sku"",""maxLength"":100},{""name"":""SerialNumber"",""type"":""string"",""displayName"":""SerialNumber"",""maxLength"":100}],""displayName"":""Product""}},""displayName"":""Items""}],""displayName"":""Shipment Manifest Received""}");
		private string _SourceSystemId;
		private string _EventId;
		private string _Timestamp;
		private string _PurchaseOrderNumber;
		private int _DeliveryLocation;
		private IList<Sample.Contracts.Product> _Items;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ShipmentManifestReceived._SCHEMA;
			}
		}
		public string SourceSystemId
		{
			get
			{
				return this._SourceSystemId;
			}
			set
			{
				this._SourceSystemId = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public string Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public string PurchaseOrderNumber
		{
			get
			{
				return this._PurchaseOrderNumber;
			}
			set
			{
				this._PurchaseOrderNumber = value;
			}
		}
		public int DeliveryLocation
		{
			get
			{
				return this._DeliveryLocation;
			}
			set
			{
				this._DeliveryLocation = value;
			}
		}
		public IList<Sample.Contracts.Product> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.SourceSystemId;
			case 1: return this.EventId;
			case 2: return this.Timestamp;
			case 3: return this.PurchaseOrderNumber;
			case 4: return this.DeliveryLocation;
			case 5: return this.Items;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.SourceSystemId = (System.String)fieldValue; break;
			case 1: this.EventId = (System.String)fieldValue; break;
			case 2: this.Timestamp = (System.String)fieldValue; break;
			case 3: this.PurchaseOrderNumber = (System.String)fieldValue; break;
			case 4: this.DeliveryLocation = (System.Int32)fieldValue; break;
			case 5: this.Items = (IList<Sample.Contracts.Product>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
